name: Market Analysis 15m (Wilder)

on:
  workflow_dispatch:
    inputs:
      symbols:
        description: "Kommagetrennte Symbole (z. B. EURUSD=X,GBPUSD=X)"
        required: false
        default: "EURUSD=X"
      tz:
        description: "Zeitzone (IANA, z. B. Europe/Berlin)"
        required: false
        default: "Europe/Berlin"
  schedule:
    - cron: "*/15 * * * *"   # alle 15 Minuten

jobs:
  run:
    runs-on: ubuntu-latest

    # 🔐 ZENTRAL: Mail-Variablen + PYTHONPATH
    env:
      PYTHONPATH: ${{ github.workspace }}
      SMTP_USER:  ${{ secrets.SMTP_USER }}
      SMTP_PASS:  ${{ secrets.SMTP_PASS }}
      EMAIL_TO:   ${{ secrets.EMAIL_TO }}
      SMTP_HOST:  ${{ secrets.SMTP_HOST }}
      SMTP_PORT:  ${{ secrets.SMTP_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          set -e
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Safety-Nets, falls requirements.txt mal schlanker ist:
          pip install python-dotenv pyyaml

      # --- Optionaler Guard: am Wochenende skippen (Agent selbst hat Fallback auf Daily) ---
      # - name: Skip on weekend (UTC)
      #   run: |
      #     DOW=$(date -u +%u)   # 1=Mo … 7=So
      #     if [ "$DOW" -ge 6 ]; then
      #       echo "Weekend (UTC) – skip run."
      #       exit 78
      #     fi

      - name: Debug mail env (masked)
        run: |
          python - <<'PY'
          import os
          def mask(v): 
              return v if not v else (v[:2] + "***" + v[-2:])
          print("[env] EMAIL_TO  =", mask(os.getenv("EMAIL_TO")))
          print("[env] SMTP_USER =", mask(os.getenv("SMTP_USER")))
          print("[env] SMTP_PASS =", "JA" if os.getenv("SMTP_PASS") else "NEIN")
          print("[env] HOST/PORT =", os.getenv("SMTP_HOST"), os.getenv("SMTP_PORT"))
          PY

      - name: Run AGENT (send email)
        run: |
          set -euxo pipefail
          SYM="${{ github.event.inputs.symbols }}"
          TZV="${{ github.event.inputs.tz }}"
          [ -z "$SYM" ] && SYM="EURUSD=X"
          [ -z "$TZV" ] && TZV="Europe/Berlin"

          echo "[run] symbols=$SYM tz=$TZV"
          python -u agent.py --symbols "$SYM" --tz "$TZV" --email
          echo "[AGENT_DONE] agent.py finished"

      - name: Upload charts (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: charts
          path: reports/out/*.png
          if-no-files-found: ignore
