name: Market Analysis 15m (force run)

on:
  workflow_dispatch:
    inputs:
      symbols:
        description: "Kommagetrennte Symbole (z.B. EURUSD=X,GBPUSD=X)"
        required: false
        default: "EURUSD=X"
      tz:
        description: "Zeitzone (IANA, z.B. Europe/Berlin)"
        required: false
        default: "Europe/Berlin"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps (robust)
        run: |
          set -e
          echo "Python: $(python -V)"
          python -m pip install --upgrade pip
          pip --version

          # Erst normal installieren
          pip install --no-cache-dir -r requirements.txt || true

          # Falls pandas-ta fehlt → PyPI versuchen
          python - <<'PY'
          import importlib, sys, subprocess
          def have(mod):
              try: importlib.import_module(mod); print(f"[ok] {mod} vorhanden"); return True
              except: return False
          if not have("pandas_ta"):
              print("[fix] Installing pandas-ta via PyPI…")
              subprocess.check_call([sys.executable, "-m", "pip", "install", "pandas-ta==0.3.14b0"])
          PY

          # Falls das auch scheitert → GitHub Source
          python - <<'PY'
          import importlib, subprocess, sys
          try:
              importlib.import_module("pandas_ta")
              print("[ok] pandas-ta import works.")
          except Exception:
              print("[fix] Installing pandas-ta from GitHub source…")
              subprocess.check_call([sys.executable, "-m", "pip", "install", "git+https://github.com/twopirllc/pandas-ta.git@main"])
          PY

      - name: Run AGENT (send email)
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:  ${{ secrets.EMAIL_TO }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          python agent.py --symbols "${{ github.event.inputs.symbols }}" --tz "${{ github.event.inputs.tz }}" --email
