      - name: Install deps (robust)
        run: |
          set -e
          echo "Python: $(python -V)"
          python -m pip install --upgrade pip
          pip --version

          # 1) Erst normal, ohne Cache (vermeidet kaputte Wheels)
          pip install --no-cache-dir -r requirements.txt || true

          # 2) Falls pandas-ta immer noch fehlt/fehlerhaft → PyPI-Versuch
          python - <<'PY'
          import importlib, sys, subprocess
          def have(mod): 
              try: importlib.import_module(mod); return True
              except Exception: return False

          if not have("pandas_ta"):
              print("[fix] Trying PyPI: pandas-ta==0.3.14b0 …")
              subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-cache-dir", "pandas-ta==0.3.14b0"])

          # 3) Falls das auch scheitert → GitHub-Source (tag v0.3.14b)
          try:
              importlib.import_module("pandas_ta")
              print("[ok] pandas_ta import works.")
          except Exception:
              print("[fix] Trying GitHub source for pandas_ta (v0.3.14b) …")
              subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-cache-dir",
                                    "git+https://github.com/twopirllc/pandas-ta@v0.3.14b"])
              importlib.import_module("pandas_ta")
              print("[ok] pandas_ta import works after GitHub install.")
          PY
